// Date: 11.02.2016 19:10:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package XFactHD.rfutilities.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDiodeFloat extends ModelBase
{
  //fields
    ModelRenderer ConnectorLeft;
    ModelRenderer ConnectorRight;
    ModelRenderer WireLeft;
    ModelRenderer WireRight;
    ModelRenderer Diode;
  
  public ModelDiodeFloat()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      ConnectorLeft = new ModelRenderer(this, 36, 0);
      ConnectorLeft.addBox(0F, 0F, 0F, 1, 6, 6);
      ConnectorLeft.setRotationPoint(-8F, 12F, -3F);
      ConnectorLeft.setTextureSize(64, 32);
      ConnectorLeft.mirror = true;
      setRotation(ConnectorLeft, 0F, 0F, 0F);
      ConnectorRight = new ModelRenderer(this, 50, 0);
      ConnectorRight.addBox(0F, 0F, 0F, 1, 6, 6);
      ConnectorRight.setRotationPoint(7F, 12F, -3F);
      ConnectorRight.setTextureSize(64, 32);
      ConnectorRight.mirror = true;
      setRotation(ConnectorRight, 0F, 0F, 0F);
      WireLeft = new ModelRenderer(this, 0, 8);
      WireLeft.addBox(0F, 0F, 0F, 2, 2, 2);
      WireLeft.setRotationPoint(-7F, 14F, -1F);
      WireLeft.setTextureSize(64, 32);
      WireLeft.mirror = true;
      setRotation(WireLeft, 0F, 0F, 0F);
      WireRight = new ModelRenderer(this, 8, 8);
      WireRight.addBox(0F, 0F, 0F, 2, 2, 2);
      WireRight.setRotationPoint(5F, 14F, -1F);
      WireRight.setTextureSize(64, 32);
      WireRight.mirror = true;
      setRotation(WireRight, 0F, 0F, 0F);
      Diode = new ModelRenderer(this, 0, 0);
      Diode.addBox(0F, 0F, 0F, 10, 4, 4);
      Diode.setRotationPoint(-5F, 13F, -2F);
      Diode.setTextureSize(64, 32);
      Diode.mirror = true;
      setRotation(Diode, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ConnectorLeft.render(f5);
    ConnectorRight.render(f5);
    WireLeft.render(f5);
    WireRight.render(f5);
    Diode.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
